### PR TITLE
Browserify implementation and preparation for splitting into several files.

### PR DESCRIPTION
**Pull request by MarkusBordihn**
@davidbau 
This is the first step for #99 and I tried to leave most of the current structure untouched.
The src/... folder is containing the real source code.
The "jquery-turtle.js" and "jquery-turtle.min.js" are generated out of the src/...

### CODE REVIEW

**Comment by davidbau** [comment]
Hm, you moved jquery-turtle.js to src/jquery-turtle.js, but git doesn't have the history that way: it has you replacing more than 10,000 lines of jquery-turtle.js and creating 10,000 new lines in src.

Can you rearrange the history so that the history on that file is correctly preserved?

**Comment by MarkusBordihn** [comment]
I could only preserve the history by.
1) rename the jquery-turtle.js in the parent folder
or
2.) I created the generated code in another folder like "dist"

Please let me know which you preferred ?

**Comment by MarkusBordihn** [comment]
I will check later if git is providing an option to copy the history or I will to this in two steps.

**Comment by MarkusBordihn** [comment]
Created new pull request #104 with the correct git history.

**Pull request closed without merging**
