### PR TITLE
Change trig functions to operate in radians; add degree trig functions

### PR DESCRIPTION
**Pull request by bobcassels**
We change the existing trig functions to operate in radians. We add sind, cosd, etc. as functions that operate in degrees. This follows Fortran, MATLAB, Wolfram Alpha, etc.

In addition, we remove atan2, and move its functionality to the 2-arg variants of atan and atand. This follows Lisp and Scheme, and is appropriate since CoffeeScript has optional arguments with default values. atan(y, x = 1) == atan2(y, x)

And we fix the accuracy of these functions by removing their use of roundEpsilon. That function seems to be trying to ensure that values that should be rational (e.g. sind 30 == .5), look "nice". Instead, we just explicitly check for such values. The fact that there is a small number of such values is ensured by http://www.jstor.org/stable/2304540.

### CODE REVIEW

**Comment by davidbau** [comment]
This is cool.  Since it's a breaking change it'd be nice for us to do two things:
(1) Write a short blog entry (mostly so that we have a web page where we can point people who are confused)
https://github.com/PencilCode/blog/tree/master/documents/posts

(2) Do a short sed script to change exiting bare sin(90) to sind(90).

Here is a list of egrep results of code that matches sin|cos|tan|atan etc.

http://david.pencilcode.net/home/maybebroken.txt

**Comment by bobcassels** [comment]
# Here's a python3 program that will make the appropriate changes.
# You will want to change it to do the right thing to actually update the database,
# probably by removing the filter to check for particular functions (used for debugging),
# changing the file name handling, and writing unchanged lines.

import re
import string

files_to_skip = [# Code is in an unfinished state. Looks like it wants to be in radians.
                 "belto15/Conic_Sections",
                 # Copies of jquery-turtle.js:
                 "dkogan/myjquery_turtle.js",
                 "drm/my_jquery_turtle.js",
                 # Uses sin, looks confused.
                 "belto15/Blood_pressure",
                 # Just confused.
                 "misterv/Experiments/Experiment/Triginometry",
                 # This code is just confused. It uses tan, but probably wants to be using atand.
                 "monaghant15/DirectionTest"]

# A bunch of these use Math.sin, but use sin as a variable name.
degrees_to_radians = re.compile('degrees[-_]?(to)?[-_]?radians|D_2_R|degrees', re.I)

file_line = re.compile('^(.*?):(.*)$')
trig_line = re.compile('^(.*?\\b)(sin|cos|tan|asin|acos|atan|atan2)(\\b.*)$')
turtle_color_operation = re.compile('\\b(pen|dot|polygon|background|color|fill|box|wear)\\b')

def all_whitespace(s):
    return s.strip(string.whitespace) == ''

def fix(line):
    match_trig = re.match(trig_line, line)
    if match_trig:
        start = match_trig.group(1)
        trig_function = match_trig.group(2)
        rest = match_trig.group(3)
        if start.endswith('.') or rest.startswith(':') or     \
           re.search('["\']', start) or                       \
           re.search('["\']', rest) or                        \
           trig_function == 'sin' and                         \
           (start.endswith('unpardonable ')) or               \
           trig_function == 'tan' and                         \
           (re.search(turtle_color_operation, start) or             \
            rest.startswith(' sneakers') or                   \
            re.search('\\bbeige\\b', start) or                \
            all_whitespace(start) and all_whitespace(rest) or \
            re.search('\\[', start) or re.search('\\]', rest)):
            return start + trig_function + fix(rest)
        else:
            if trig_function == 'atan2':
                trig_function = 'atan'
            return start + trig_function + 'd' + fix(rest)
    else:
        return line

with open('/Users/bcassels/Downloads/maybebroken.txt') as input:
    with open('/Users/bcassels/Python/test-out.txt', 'w') as output:
        for line in input:
            match_line = re.match(file_line, line)
            if match_line:
                file = match_line.group(1)
                if not(file in files_to_skip or              \
                       file.endswith('.html') or             \
                       re.search(degrees_to_radians, file)):
                    code = match_line.group(2)
                    match_trig = re.match(trig_line, code)
                    if match_trig and match_trig.group(2) == 'tan':
                        output.write(file + ':' + fix(code) + '\n')

**Comment by bobcassels** [comment]
Here's my blog post explaining the change:

https://docs.google.com/a/google.com/document/d/1YskbkZBJunG-T4hlJih_2sSyZ1UkOQ6AwpQ9ZxiCrow/edit

**Comment by davidbau** [comment]
Thanks bob!  Send me your conversion script.  Also I'll be doing the log->debug change soon.

**Pull request merged**
